server.port: 9966
spring.profiles: default
app.security.jwt:
  tokenExpirationTime: 15 # Number of minutes
  refreshTokenExpTime: 60 # Minutes
  tokenIssuer: http://gurkan.com
  tokenSigningKey: IiOiJ0ZXN0QGdtYWlsLmNvbSIsInNjb3BlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9QUkVNSVVNX01FTU
  
spring.datasource:
  url: jdbc:mysql://localhost:3306/testDB?useSSL=false
  username: gurkan
  password: gurkan
  data: "classpath*:data.sql"
spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate.ddl-auto: create
  show-sql: true